### ISSUE TITLE
Style example not working because of missing exported fields

### ISSUE THREAD

**Issue by PMunch** [xmonader/nim-terminaltables#1]
I tried to run the custom style example from the README and it doesn't work because neither the `Style` type nor the `style` field of the `TerminalTable` type is exported.

**Comment by xmonader** [comment]
Sorry for the inconvenience. Fixed in https://github.com/xmonader/nim-terminaltables/commit/fd68775e1ba8d5d50d5bc874ee56ed14782a1a06

**Comment by PMunch** [comment]
Well that was quick!
