### ISSUE TITLE
Sorting table before printing?

### ISSUE THREAD

**Issue by telatin** [xmonader/nim-terminaltables#8]
Hello,

I'm quite new to nim so maybe there's an obvious way to do this. What I'm trying to do is sorting by a column the table after accumulating its rows. Is this possible?

**Comment by xmonader** [comment]
Hello @telatin, you can create a temp array (sorted of your original data array)  using [sort](https://nim-lang.org/docs/algorithm.html#basic-usage) then feed that sorted array to the table
